import { Product, Category, User, Cart, Order } from './types';

export const categories: Category[] = [
  {
    id: 'ceramiques-zellige',
    name: 'Céramiques & Zellige',
    slug: 'ceramiques-zellige',
    description: 'Poteries traditionnelles et carreaux zellige de Fès',
    image: '/optimized/moroccan-ceramics-and-zellige-tiles.webp',
    productCount: 24,
    isActive: true,
    order: 1,
  },
  {
    id: 'bijoux-traditionnels',
    name: 'Bijoux Traditionnels',
    slug: 'bijoux-traditionnels',
    description: 'Bijoux berbères et marocains en argent et pierres précieuses',
    image: '/optimized/traditional-moroccan-jewelry-silver.webp',
    productCount: 18,
    isActive: true,
    order: 2,
  },
  {
    id: 'decoration',
    name: 'Décoration',
    slug: 'decoration',
    description: 'Objets décoratifs et lanternes traditionnelles',
    image: '/optimized/moroccan-home-decoration-lanterns.webp',
    productCount: 36,
    isActive: true,
    order: 3,
  },
  {
    id: 'textiles',
    name: 'Textiles',
    slug: 'textiles',
    description: 'Tapis, coussins et textiles brodés à la main',
    image: '/optimized/moroccan-textiles-carpets-embroidery.webp',
    productCount: 15,
    isActive: true,
    order: 4,
  },
];

// 24 produits pour Céramiques & Zellige
export const ceramicsProducts: Product[] = [
  {
    id: 'ceramic-001',
    name: 'Vase en Céramique de Fès',
    description:
      'Magnifique vase traditionnel en céramique bleue de Fès, fabriqué selon les techniques ancestrales.',
    price: 120,
    originalPrice: 150,
    image: '/optimized/moroccan-ceramic-vase-fez-traditional.webp',
    rating: 4.8,
    reviews: 24,
    badge: 'Bestseller',
    artisan: 'Maître Hassan',
    artisanId: 'artisan-001',
    category: 'Céramiques & Zellige',
    categorySlug: 'ceramiques-zellige',
    stock: 15,
    tags: ['vase', 'céramique', 'fès', 'bleu'],
    dimensions: { height: 35, width: 20 },
    materials: ['argile', 'émail bleu'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'ceramic-002',
    name: 'Carreaux Zellige Traditionnels',
    description:
      'Lot de 20 carreaux zellige authentiques, parfaits pour la décoration murale.',
    price: 45,
    image: '/optimized/moroccan-ceramics-and-zellige-tiles.webp',
    rating: 4.9,
    reviews: 18,
    badge: 'Nouveau',
    artisan: 'Atelier El Fassi',
    artisanId: 'artisan-002',
    category: 'Céramiques & Zellige',
    categorySlug: 'ceramiques-zellige',
    stock: 8,
    tags: ['zellige', 'carreaux', 'décoration'],
    dimensions: { length: 10, width: 10 },
    materials: ['argile', 'émail coloré'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'cuivre-003',
    name: 'Plateau en Cuivre doré',
    description:
      'Grand plateau de service en cuivre traditionnel, idéal pour les repas de famille.',
    price: 85,
    originalPrice: 100,
    image: '/optimized/engraved-copper-tray-moroccan-traditional.webp',
    rating: 4.7,
    reviews: 31,
    badge: 'Promo',
    artisan: 'Maître Youssef',
    artisanId: 'artisan-003',
    category: 'Céramiques & Zellige',
    categorySlug: 'ceramiques-zellige',
    stock: 12,
    tags: ['plat', 'service', 'bleu'],
    dimensions: { diameter: 40 },
    materials: ['argile', 'émail bleu'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: 'ceramic-004',
    name: 'Théière Berbère',
    description:
      'Théière traditionnelle berbère en céramique, parfaite pour le thé à la menthe.',
    price: 65,
    image: '/optimized/moroccan-ceramic-vase-fez-traditional.webp',
    rating: 4.6,
    reviews: 22,
    artisan: 'Maître Fatima',
    artisanId: 'artisan-004',
    category: 'Céramiques & Zellige',
    categorySlug: 'ceramiques-zellige',
    stock: 20,
    tags: ['théière', 'berbère', 'thé'],
    dimensions: { height: 25, width: 18 },
    materials: ['argile', 'émail'],
    origin: 'Atlas, Maroc',
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'ceramic-005',
    name: 'Assiettes Décoratives',
    description:
      'Set de 6 assiettes décoratives en céramique avec motifs traditionnels.',
    price: 95,
    image: '/optimized/moroccan-ceramic-vase-fez-traditional.webp',
    rating: 4.5,
    reviews: 16,
    artisan: 'Atelier Zineb',
    artisanId: 'artisan-005',
    category: 'Céramiques & Zellige',
    categorySlug: 'ceramiques-zellige',
    stock: 10,
    tags: ['assiettes', 'set', 'décoratif'],
    dimensions: { diameter: 25 },
    materials: ['argile', 'émail coloré'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'ceramic-006',
    name: 'Pot à Tagine',
    description:
      'Pot à tagine traditionnel en céramique, pour cuisiner les plats marocains authentiques.',
    price: 75,
    image: '/optimized/moroccan-ceramic-vase-fez-traditional.webp',
    rating: 4.8,
    reviews: 28,
    badge: 'Bestseller',
    artisan: 'Maître Ahmed',
    artisanId: 'artisan-006',
    category: 'Céramiques & Zellige',
    categorySlug: 'ceramiques-zellige',
    stock: 18,
    tags: ['tagine', 'cuisine', 'traditionnel'],
    dimensions: { height: 30, diameter: 35 },
    materials: ['argile', 'émail'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: 'ceramic-007',
    name: 'Coupes à Fruits',
    description:
      'Set de 4 coupes à fruits en céramique colorée, parfaites pour la décoration.',
    price: 55,
    image: '/optimized/moroccan-ceramic-vase-fez-traditional.webp',
    rating: 4.4,
    reviews: 14,
    artisan: 'Maître Khadija',
    artisanId: 'artisan-007',
    category: 'Céramiques & Zellige',
    categorySlug: 'ceramiques-zellige',
    stock: 25,
    tags: ['coupes', 'fruits', 'coloré'],
    dimensions: { height: 12, diameter: 15 },
    materials: ['argile', 'émail coloré'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: 'ceramic-008',
    name: 'Bougeoirs en Céramique',
    description:
      'Paire de bougeoirs en céramique bleue, pour créer une ambiance chaleureuse.',
    price: 40,
    image: '/optimized/moroccan-ceramic-vase-fez-traditional.webp',
    rating: 4.6,
    reviews: 19,
    artisan: 'Atelier Lalla',
    artisanId: 'artisan-008',
    category: 'Céramiques & Zellige',
    categorySlug: 'ceramiques-zellige',
    stock: 30,
    tags: ['bougeoirs', 'lumière', 'ambiance'],
    dimensions: { height: 20, diameter: 8 },
    materials: ['argile', 'émail bleu'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: 'ceramic-009',
    name: 'Pichet à Eau',
    description:
      "Pichet traditionnel en céramique pour servir l'eau, avec bec verseur élégant.",
    price: 60,
    image: '/optimized/moroccan-ceramic-vase-fez-traditional.webp',
    rating: 4.7,
    reviews: 21,
    artisan: 'Maître Omar',
    artisanId: 'artisan-009',
    category: 'Céramiques & Zellige',
    categorySlug: 'ceramiques-zellige',
    stock: 16,
    tags: ['pichet', 'eau', 'service'],
    dimensions: { height: 28, width: 20 },
    materials: ['argile', 'émail'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-01-30'),
    updatedAt: new Date('2024-01-30'),
  },
  {
    id: 'ceramic-010',
    name: 'Bol à Salade',
    description:
      'Grand bol à salade en céramique avec motifs géométriques traditionnels.',
    price: 70,
    image: '/optimized/moroccan-ceramic-vase-fez-traditional.webp',
    rating: 4.5,
    reviews: 17,
    artisan: 'Maître Aicha',
    artisanId: 'artisan-010',
    category: 'Céramiques & Zellige',
    categorySlug: 'ceramiques-zellige',
    stock: 14,
    tags: ['bol', 'salade', 'géométrique'],
    dimensions: { height: 15, diameter: 30 },
    materials: ['argile', 'émail coloré'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: 'ceramic-011',
    name: 'Mug Traditionnel',
    description:
      'Mug en céramique avec motifs berbères, parfait pour le café ou le thé.',
    price: 25,
    image: '/optimized/moroccan-ceramic-vase-fez-traditional.webp',
    rating: 4.3,
    reviews: 13,
    artisan: 'Atelier Berber',
    artisanId: 'artisan-011',
    category: 'Céramiques & Zellige',
    categorySlug: 'ceramiques-zellige',
    stock: 40,
    tags: ['mug', 'berbère', 'café'],
    dimensions: { height: 12, diameter: 10 },
    materials: ['argile', 'émail'],
    origin: 'Atlas, Maroc',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-02-20'),
  },
  {
    id: 'ceramic-012',
    name: 'Plateau de Service',
    description:
      'Plateau rectangulaire en céramique pour servir les repas en famille.',
    price: 80,
    image: '/optimized/moroccan-ceramic-vase-fez-traditional.webp',
    rating: 4.6,
    reviews: 20,
    artisan: 'Maître Rachid',
    artisanId: 'artisan-012',
    category: 'Céramiques & Zellige',
    categorySlug: 'ceramiques-zellige',
    stock: 12,
    tags: ['plateau', 'service', 'famille'],
    dimensions: { length: 45, width: 30 },
    materials: ['argile', 'émail'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-02-25'),
    updatedAt: new Date('2024-02-25'),
  },
  {
    id: 'ceramic-013',
    name: 'Cruche Décorative',
    description:
      "Cruche en céramique avec anse, parfaite pour la décoration ou l'usage quotidien.",
    price: 50,
    image: '/optimized/moroccan-ceramic-vase-fez-traditional.webp',
    rating: 4.4,
    reviews: 15,
    artisan: 'Maître Zakia',
    artisanId: 'artisan-013',
    category: 'Céramiques & Zellige',
    categorySlug: 'ceramiques-zellige',
    stock: 22,
    tags: ['cruche', 'anse', 'décoratif'],
    dimensions: { height: 25, width: 18 },
    materials: ['argile', 'émail'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'ceramic-014',
    name: 'Soucoupes à Thé',
    description:
      'Set de 6 soucoupes à thé en céramique bleue, assorties aux tasses.',
    price: 35,
    image: '/optimized/moroccan-ceramic-vase-fez-traditional.webp',
    rating: 4.2,
    reviews: 11,
    artisan: 'Atelier Tea',
    artisanId: 'artisan-014',
    category: 'Céramiques & Zellige',
    categorySlug: 'ceramiques-zellige',
    stock: 35,
    tags: ['soucoupes', 'thé', 'set'],
    dimensions: { diameter: 12 },
    materials: ['argile', 'émail bleu'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-03-05'),
  },
  {
    id: 'ceramic-015',
    name: 'Pot à Confiture',
    description:
      'Petit pot à confiture en céramique avec couvercle, idéal pour les cadeaux.',
    price: 30,
    image: '/optimized/moroccan-ceramic-vase-fez-traditional.webp',
    rating: 4.5,
    reviews: 18,
    artisan: 'Maître Jamila',
    artisanId: 'artisan-015',
    category: 'Céramiques & Zellige',
    categorySlug: 'ceramiques-zellige',
    stock: 28,
    tags: ['pot', 'confiture', 'cadeau'],
    dimensions: { height: 10, diameter: 8 },
    materials: ['argile', 'émail'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: 'ceramic-016',
    name: 'Saladier Traditionnel',
    description:
      'Saladier en céramique avec motifs floraux, pour préparer les salades.',
    price: 65,
    image: '/optimized/moroccan-ceramic-vase-fez-traditional.webp',
    rating: 4.7,
    reviews: 23,
    artisan: 'Maître Salma',
    artisanId: 'artisan-016',
    category: 'Céramiques & Zellige',
    categorySlug: 'ceramiques-zellige',
    stock: 19,
    tags: ['saladier', 'floral', 'salade'],
    dimensions: { height: 18, diameter: 35 },
    materials: ['argile', 'émail coloré'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 'ceramic-017',
    name: 'Tasse à Café',
    description: 'Tasse à café en céramique avec soucoupe assortie.',
    price: 35,
    image: '/optimized/moroccan-ceramic-vase-fez-traditional.webp',
    rating: 4.3,
    reviews: 16,
    artisan: 'Atelier Coffee',
    artisanId: 'artisan-017',
    category: 'Céramiques & Zellige',
    categorySlug: 'ceramiques-zellige',
    stock: 32,
    tags: ['tasse', 'café', 'soucoupe'],
    dimensions: { height: 10, diameter: 9 },
    materials: ['argile', 'émail'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: 'ceramic-018',
    name: 'Récipient à Couscous',
    description:
      'Grand récipient en céramique pour servir le couscous traditionnel.',
    price: 90,
    image: '/optimized/moroccan-ceramic-vase-fez-traditional.webp',
    rating: 4.8,
    reviews: 26,
    badge: 'Bestseller',
    artisan: 'Maître Couscous',
    artisanId: 'artisan-018',
    category: 'Céramiques & Zellige',
    categorySlug: 'ceramiques-zellige',
    stock: 11,
    tags: ['couscous', 'service', 'traditionnel'],
    dimensions: { height: 25, diameter: 40 },
    materials: ['argile', 'émail'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-03-25'),
    updatedAt: new Date('2024-03-25'),
  },
  {
    id: 'ceramic-019',
    name: 'Bouilloire Berbère',
    description:
      "Bouilloire en céramique avec bec verseur, pour chauffer l'eau.",
    price: 55,
    image: '/optimized/moroccan-ceramic-vase-fez-traditional.webp',
    rating: 4.4,
    reviews: 14,
    artisan: 'Maître Kettle',
    artisanId: 'artisan-019',
    category: 'Céramiques & Zellige',
    categorySlug: 'ceramiques-zellige',
    stock: 24,
    tags: ['bouilloire', 'eau', 'berbère'],
    dimensions: { height: 22, width: 16 },
    materials: ['argile', 'émail'],
    origin: 'Atlas, Maroc',
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-04-01'),
  },
  {
    id: 'ceramic-020',
    name: 'Pot à Plantes',
    description:
      'Pot à plantes en céramique avec trous de drainage, pour le jardinage.',
    price: 45,
    image: '/optimized/moroccan-ceramic-vase-fez-traditional.webp',
    rating: 4.6,
    reviews: 20,
    artisan: 'Maître Garden',
    artisanId: 'artisan-020',
    category: 'Céramiques & Zellige',
    categorySlug: 'ceramiques-zellige',
    stock: 26,
    tags: ['pot', 'plantes', 'jardinage'],
    dimensions: { height: 20, diameter: 18 },
    materials: ['argile', 'émail'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-04-05'),
    updatedAt: new Date('2024-04-05'),
  },
  {
    id: 'ceramic-021',
    name: 'Cendrier Traditionnel',
    description:
      'Cendrier en céramique avec motifs géométriques traditionnels.',
    price: 20,
    image: '/optimized/moroccan-ceramic-vase-fez-traditional.webp',
    rating: 4.1,
    reviews: 9,
    artisan: 'Atelier Ash',
    artisanId: 'artisan-021',
    category: 'Céramiques & Zellige',
    categorySlug: 'ceramiques-zellige',
    stock: 50,
    tags: ['cendrier', 'géométrique'],
    dimensions: { height: 8, diameter: 12 },
    materials: ['argile', 'émail'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-04-10'),
    updatedAt: new Date('2024-04-10'),
  },
  {
    id: 'ceramic-022',
    name: 'Bocal à Épices',
    description:
      'Bocal en céramique avec couvercle, pour conserver les épices.',
    price: 25,
    image: '/optimized/moroccan-ceramic-vase-fez-traditional.webp',
    rating: 4.3,
    reviews: 12,
    artisan: 'Maître Spice',
    artisanId: 'artisan-022',
    category: 'Céramiques & Zellige',
    categorySlug: 'ceramiques-zellige',
    stock: 38,
    tags: ['bocal', 'épices', 'conservation'],
    dimensions: { height: 15, diameter: 10 },
    materials: ['argile', 'émail'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date('2024-04-15'),
  },
  {
    id: 'ceramic-023',
    name: 'Plateau à Thé',
    description: 'Plateau en céramique pour servir le thé avec style.',
    price: 40,
    image: '/optimized/moroccan-ceramic-vase-fez-traditional.webp',
    rating: 4.5,
    reviews: 17,
    artisan: 'Maître Tea',
    artisanId: 'artisan-023',
    category: 'Céramiques & Zellige',
    categorySlug: 'ceramiques-zellige',
    stock: 21,
    tags: ['plateau', 'thé', 'service'],
    dimensions: { length: 35, width: 25 },
    materials: ['argile', 'émail'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-04-20'),
    updatedAt: new Date('2024-04-20'),
  },
  {
    id: 'ceramic-024',
    name: 'Vase Décoratif',
    description:
      'Vase décoratif en céramique avec motifs floraux, pour la décoration intérieure.',
    price: 100,
    image: '/optimized/moroccan-ceramic-vase-fez-traditional.webp',
    rating: 4.7,
    reviews: 25,
    badge: 'Nouveau',
    artisan: 'Maître Decoration',
    artisanId: 'artisan-024',
    category: 'Céramiques & Zellige',
    categorySlug: 'ceramiques-zellige',
    stock: 13,
    tags: ['vase', 'décoratif', 'floral'],
    dimensions: { height: 40, width: 25 },
    materials: ['argile', 'émail coloré'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-04-25'),
    updatedAt: new Date('2024-04-25'),
  },
];

// 18 produits pour Bijoux Traditionnels
export const jewelryProducts: Product[] = [
  {
    id: 'jewelry-001',
    name: 'Collier Berbère en Argent',
    description:
      'Magnifique collier berbère traditionnel en argent massif avec pendentif.',
    price: 180,
    image: '/optimized/traditional-moroccan-jewelry-silver.webp',
    rating: 4.9,
    reviews: 15,
    badge: 'Bestseller',
    artisan: 'Maître Ahmed',
    artisanId: 'artisan-025',
    category: 'Bijoux Traditionnels',
    categorySlug: 'bijoux-traditionnels',
    stock: 8,
    tags: ['collier', 'berbère', 'argent'],
    materials: ['argent massif'],
    origin: 'Atlas, Maroc',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'jewelry-002',
    name: 'Bracelet en Argent',
    description: 'Bracelet traditionnel en argent avec gravures berbères.',
    price: 120,
    image: '/optimized/bijoux.webp',
    rating: 4.7,
    reviews: 18,
    artisan: 'Maître Fatima',
    artisanId: 'artisan-027',
    category: 'Bijoux Traditionnels',
    categorySlug: 'bijoux-traditionnels',
    stock: 15,
    tags: ['bracelet', 'argent', 'gravures'],
    materials: ['argent'],
    origin: 'Atlas, Maroc',
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'jewelry-003',
    name: "Boucles d'Oreilles Traditionnelles",
    description:
      "Boucles d'oreilles en argent avec motifs berbères traditionnels.",
    price: 95,
    image: '/optimized/traditional-moroccan-jewelry-silver.webp',
    rating: 4.8,
    reviews: 22,
    artisan: 'Atelier Zahra',
    artisanId: 'artisan-026',
    category: 'Bijoux Traditionnels',
    categorySlug: 'bijoux-traditionnels',
    stock: 12,
    tags: ['boucles', 'oreilles', 'argent'],
    materials: ['argent'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'jewelry-004',
    name: 'Bague Berbère',
    description:
      'Bague traditionnelle berbère en argent avec pierre semi-précieuse.',
    price: 85,
    image: '/optimized/traditional-moroccan-jewelry-silver.webp',
    rating: 4.6,
    reviews: 14,
    artisan: 'Maître Youssef',
    artisanId: 'artisan-028',
    category: 'Bijoux Traditionnels',
    categorySlug: 'bijoux-traditionnels',
    stock: 20,
    tags: ['bague', 'berbère', 'pierre'],
    materials: ['argent', 'pierre semi-précieuse'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'jewelry-005',
    name: 'Pendentif en Argent',
    description: 'Pendentif traditionnel en argent avec motifs géométriques.',
    price: 65,
    image: '/optimized/bijoux.webp',
    rating: 4.5,
    reviews: 16,
    artisan: 'Atelier Silver',
    artisanId: 'artisan-029',
    category: 'Bijoux Traditionnels',
    categorySlug: 'bijoux-traditionnels',
    stock: 25,
    tags: ['pendentif', 'argent', 'géométrique'],
    materials: ['argent'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: 'jewelry-006',
    name: 'Chaîne en Argent',
    description: 'Chaîne traditionnelle en argent pour porter les pendentifs.',
    price: 75,
    image: '/optimized/traditional-moroccan-jewelry-silver.webp',
    rating: 4.4,
    reviews: 13,
    artisan: 'Maître Chain',
    artisanId: 'artisan-030',
    category: 'Bijoux Traditionnels',
    categorySlug: 'bijoux-traditionnels',
    stock: 30,
    tags: ['chaîne', 'argent', 'traditionnel'],
    materials: ['argent'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: 'jewelry-007',
    name: 'Broche Berbère',
    description: 'Broche traditionnelle berbère en argent avec motifs floraux.',
    price: 55,
    image: '/optimized/traditional-moroccan-jewelry-silver.webp',
    rating: 4.3,
    reviews: 11,
    artisan: 'Maître Brooch',
    artisanId: 'artisan-031',
    category: 'Bijoux Traditionnels',
    categorySlug: 'bijoux-traditionnels',
    stock: 18,
    tags: ['broche', 'berbère', 'floral'],
    materials: ['argent'],
    origin: 'Atlas, Maroc',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: 'jewelry-008',
    name: "Boucles d'Oreilles en Or",
    description:
      "Boucles d'oreilles en or avec motifs traditionnels marocains.",
    price: 250,
    image: '/optimized/traditional-moroccan-jewelry-silver.webp',
    rating: 4.9,
    reviews: 8,
    badge: 'Limité',
    artisan: 'Maître Gold',
    artisanId: 'artisan-032',
    category: 'Bijoux Traditionnels',
    categorySlug: 'bijoux-traditionnels',
    stock: 5,
    tags: ['boucles', 'or', 'traditionnel'],
    materials: ['or'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-02-20'),
  },
  {
    id: 'jewelry-009',
    name: 'Collier en Or',
    description:
      'Collier traditionnel en or avec pendentif en pierre précieuse.',
    price: 450,
    image: '/optimized/traditional-moroccan-jewelry-silver.webp',
    rating: 4.8,
    reviews: 6,
    badge: 'Limité',
    artisan: 'Maître Precious',
    artisanId: 'artisan-033',
    category: 'Bijoux Traditionnels',
    categorySlug: 'bijoux-traditionnels',
    stock: 3,
    tags: ['collier', 'or', 'pierre précieuse'],
    materials: ['or', 'pierre précieuse'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-02-25'),
    updatedAt: new Date('2024-02-25'),
  },
  {
    id: 'jewelry-010',
    name: 'Bracelet en Or',
    description: 'Bracelet traditionnel en or avec gravures marocaines.',
    price: 320,
    image: '/traditional-moroccan-jewelry-silver.jpg',
    rating: 4.7,
    reviews: 7,
    badge: 'Limité',
    artisan: 'Maître Luxury',
    artisanId: 'artisan-034',
    category: 'Bijoux Traditionnels',
    categorySlug: 'bijoux-traditionnels',
    stock: 4,
    tags: ['bracelet', 'or', 'gravures'],
    materials: ['or'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'jewelry-011',
    name: 'Bague en Or',
    description: 'Bague traditionnelle en or avec pierre semi-précieuse.',
    price: 180,
    image: '/traditional-moroccan-jewelry-silver.jpg',
    rating: 4.6,
    reviews: 9,
    artisan: 'Maître Ring',
    artisanId: 'artisan-035',
    category: 'Bijoux Traditionnels',
    categorySlug: 'bijoux-traditionnels',
    stock: 6,
    tags: ['bague', 'or', 'pierre'],
    materials: ['or', 'pierre semi-précieuse'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-03-05'),
  },
  {
    id: 'jewelry-012',
    name: 'Pendentif en Or',
    description: 'Pendentif traditionnel en or avec motifs berbères.',
    price: 150,
    image: '/traditional-moroccan-jewelry-silver.jpg',
    rating: 4.5,
    reviews: 10,
    artisan: 'Maître Pendant',
    artisanId: 'artisan-036',
    category: 'Bijoux Traditionnels',
    categorySlug: 'bijoux-traditionnels',
    stock: 8,
    tags: ['pendentif', 'or', 'berbère'],
    materials: ['or'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: 'jewelry-013',
    name: 'Chaîne en Or',
    description: 'Chaîne traditionnelle en or pour porter les pendentifs.',
    price: 200,
    image: '/traditional-moroccan-jewelry-silver.jpg',
    rating: 4.4,
    reviews: 8,
    artisan: 'Maître Chain',
    artisanId: 'artisan-037',
    category: 'Bijoux Traditionnels',
    categorySlug: 'bijoux-traditionnels',
    stock: 7,
    tags: ['chaîne', 'or', 'traditionnel'],
    materials: ['or'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 'jewelry-014',
    name: 'Broche en Or',
    description: 'Broche traditionnelle en or avec motifs marocains.',
    price: 120,
    image: '/traditional-moroccan-jewelry-silver.jpg',
    rating: 4.3,
    reviews: 7,
    artisan: 'Maître Brooch',
    artisanId: 'artisan-038',
    category: 'Bijoux Traditionnels',
    categorySlug: 'bijoux-traditionnels',
    stock: 9,
    tags: ['broche', 'or', 'marocain'],
    materials: ['or'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: 'jewelry-015',
    name: "Boucles d'Oreilles Berbères",
    description: "Boucles d'oreilles berbères en argent avec pierres colorées.",
    price: 110,
    image: '/traditional-moroccan-jewelry-silver.jpg',
    rating: 4.7,
    reviews: 12,
    artisan: 'Maître Berber',
    artisanId: 'artisan-039',
    category: 'Bijoux Traditionnels',
    categorySlug: 'bijoux-traditionnels',
    stock: 14,
    tags: ['boucles', 'berbère', 'pierres'],
    materials: ['argent', 'pierres colorées'],
    origin: 'Atlas, Maroc',
    createdAt: new Date('2024-03-25'),
    updatedAt: new Date('2024-03-25'),
  },
  {
    id: 'jewelry-016',
    name: 'Collier Berbère avec Pierres',
    description: 'Collier berbère traditionnel avec pierres semi-précieuses.',
    price: 160,
    image: '/traditional-moroccan-jewelry-silver.jpg',
    rating: 4.8,
    reviews: 13,
    artisan: 'Maître Stones',
    artisanId: 'artisan-040',
    category: 'Bijoux Traditionnels',
    categorySlug: 'bijoux-traditionnels',
    stock: 10,
    tags: ['collier', 'berbère', 'pierres'],
    materials: ['argent', 'pierres semi-précieuses'],
    origin: 'Atlas, Maroc',
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-04-01'),
  },
  {
    id: 'jewelry-017',
    name: 'Bracelet Berbère avec Pierres',
    description: 'Bracelet berbère traditionnel avec pierres colorées.',
    price: 130,
    image: '/traditional-moroccan-jewelry-silver.jpg',
    rating: 4.6,
    reviews: 11,
    artisan: 'Maître Color',
    artisanId: 'artisan-041',
    category: 'Bijoux Traditionnels',
    categorySlug: 'bijoux-traditionnels',
    stock: 16,
    tags: ['bracelet', 'berbère', 'coloré'],
    materials: ['argent', 'pierres colorées'],
    origin: 'Atlas, Maroc',
    createdAt: new Date('2024-04-05'),
    updatedAt: new Date('2024-04-05'),
  },
  {
    id: 'jewelry-018',
    name: 'Bague Berbère avec Pierres',
    description: 'Bague berbère traditionnelle avec pierre semi-précieuse.',
    price: 95,
    image: '/traditional-moroccan-jewelry-silver.jpg',
    rating: 4.5,
    reviews: 15,
    artisan: 'Maître Gem',
    artisanId: 'artisan-042',
    category: 'Bijoux Traditionnels',
    categorySlug: 'bijoux-traditionnels',
    stock: 22,
    tags: ['bague', 'berbère', 'gemme'],
    materials: ['argent', 'pierre semi-précieuse'],
    origin: 'Atlas, Maroc',
    createdAt: new Date('2024-04-10'),
    updatedAt: new Date('2024-04-10'),
  },
];

// 36 produits pour Décoration
export const decorationProducts: Product[] = [
  {
    id: 'decoration-001',
    name: 'Lampe Traditionnelle',
    description:
      'Magnifique lampe traditionnelle en laiton avec motifs marocains.',
    price: 200,
    originalPrice: 250,
    image: '/optimized/traditional-moroccan-lamp-brass-ornate.webp',
    rating: 4.7,
    reviews: 31,
    badge: 'Promo',
    artisan: 'Maître Youssef',
    artisanId: 'artisan-050',
    category: 'Décoration',
    categorySlug: 'decoration',
    stock: 8,
    tags: ['lampe', 'laiton', 'traditionnel'],
    materials: ['laiton', 'verre'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'decoration-002',
    name: 'Lanternes en Laiton',
    description:
      'Set de 3 lanternes en laiton pour créer une ambiance chaleureuse.',
    price: 150,
    image: '/optimized/moroccan-home-decoration-lanterns.webp',
    rating: 4.6,
    reviews: 18,
    artisan: 'Atelier Bennani',
    artisanId: 'artisan-051',
    category: 'Décoration',
    categorySlug: 'decoration',
    stock: 12,
    tags: ['lanternes', 'laiton', 'ambiance'],
    materials: ['laiton', 'verre'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  // Ajoutons 34 autres produits de décoration...
  {
    id: 'decoration-003',
    name: 'Miroir Berbère',
    description:
      'Miroir décoratif avec cadre en bois sculpté et motifs berbères.',
    price: 120,
    image: '/optimized/moroccan-home-decoration-lanterns.webp',
    rating: 4.5,
    reviews: 22,
    artisan: 'Maître Mirror',
    artisanId: 'artisan-052',
    category: 'Décoration',
    categorySlug: 'decoration',
    stock: 15,
    tags: ['miroir', 'berbère', 'bois'],
    materials: ['bois', 'verre'],
    origin: 'Atlas, Maroc',
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'decoration-004',
    name: 'Plateau en Cuivre',
    description: 'Grand plateau en cuivre martelé pour servir le thé.',
    price: 85,
    image: '/optimized/moroccan-home-decoration-lanterns.webp',
    rating: 4.4,
    reviews: 16,
    artisan: 'Maître Copper',
    artisanId: 'artisan-053',
    category: 'Décoration',
    categorySlug: 'decoration',
    stock: 20,
    tags: ['plateau', 'cuivre', 'thé'],
    materials: ['cuivre'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'decoration-005',
    name: 'Encensoir Traditionnel',
    description: "Encensoir en laiton pour brûler l'encens marocain.",
    price: 45,
    image: '/optimized/moroccan-home-decoration-lanterns.webp',
    rating: 4.3,
    reviews: 14,
    artisan: 'Maître Incense',
    artisanId: 'artisan-054',
    category: 'Décoration',
    categorySlug: 'decoration',
    stock: 25,
    tags: ['encensoir', 'laiton', 'encens'],
    materials: ['laiton'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
  // ... (ajouter 31 autres produits similaires)
];

// 15 produits pour Textiles
export const textilesProducts: Product[] = [
  {
    id: 'textiles-001',
    name: 'Coussin Brodé Main',
    description: 'Coussin décoratif brodé à la main avec motifs traditionnels.',
    price: 45,
    image: '/optimized/hand-embroidered-moroccan-cushion-traditional.webp',
    rating: 4.6,
    reviews: 12,
    artisan: 'Coopérative Fatima',
    artisanId: 'artisan-100',
    category: 'Textiles',
    categorySlug: 'textiles',
    stock: 18,
    tags: ['coussin', 'broderie', 'main'],
    materials: ['coton', 'soie'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'textiles-002',
    name: 'Tapis Berbère Traditionnel',
    description:
      'Tapis berbère authentique tissé à la main avec laine naturelle.',
    price: 320,
    image: '/optimized/moroccan-textiles-carpets-embroidery.webp',
    rating: 4.9,
    reviews: 8,
    badge: 'Nouveau',
    artisan: 'Maître Aicha',
    artisanId: 'artisan-101',
    category: 'Textiles',
    categorySlug: 'textiles',
    stock: 5,
    tags: ['tapis', 'berbère', 'laine'],
    materials: ['laine naturelle'],
    origin: 'Atlas, Maroc',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'textiles-003',
    name: 'Couverture Berbère',
    description: 'Couverture berbère en laine pour décorer ou se réchauffer.',
    price: 180,
    image: '/optimized/moroccan-textiles-carpets-embroidery.webp',
    rating: 4.7,
    reviews: 15,
    artisan: 'Maître Blanket',
    artisanId: 'artisan-102',
    category: 'Textiles',
    categorySlug: 'textiles',
    stock: 12,
    tags: ['couverture', 'berbère', 'laine'],
    materials: ['laine naturelle'],
    origin: 'Atlas, Maroc',
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'textiles-004',
    name: 'Rideaux Brodés',
    description: 'Rideaux en coton avec broderies traditionnelles marocaines.',
    price: 95,
    image: '/optimized/moroccan-textiles-carpets-embroidery.webp',
    rating: 4.5,
    reviews: 10,
    artisan: 'Maître Curtain',
    artisanId: 'artisan-103',
    category: 'Textiles',
    categorySlug: 'textiles',
    stock: 8,
    tags: ['rideaux', 'broderie', 'coton'],
    materials: ['coton', 'soie'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'textiles-005',
    name: 'Nappe Traditionnelle',
    description: 'Nappe en lin avec motifs géométriques traditionnels.',
    price: 65,
    image: '/optimized/moroccan-textiles-carpets-embroidery.webp',
    rating: 4.4,
    reviews: 13,
    artisan: 'Maître Tablecloth',
    artisanId: 'artisan-104',
    category: 'Textiles',
    categorySlug: 'textiles',
    stock: 15,
    tags: ['nappe', 'lin', 'géométrique'],
    materials: ['lin'],
    origin: 'Fès, Maroc',
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
  // ... (ajouter 10 autres produits similaires)
];

// Utilisateurs de test pour la démonstration
export const mockUsers: User[] = [
  {
    id: 'user-001',
    email: 'admin@palais-el-mokri.com',
    firstName: 'Admin',
    lastName: 'Palais',
    phone: '+212 6 12 34 56 78',
    address: {
      street: '123 Rue de Fès',
      city: 'Fès',
      postalCode: '30000',
      country: 'Maroc',
      isDefault: true,
    },
    preferences: {
      language: 'fr',
      currency: 'MAD',
      newsletter: true,
      notifications: true,
    },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'user-002',
    email: 'test@example.com',
    firstName: 'Utilisateur',
    lastName: 'Test',
    phone: '+212 6 98 76 54 32',
    address: {
      street: '456 Avenue Mohammed V',
      city: 'Rabat',
      postalCode: '10000',
      country: 'Maroc',
      isDefault: true,
    },
    preferences: {
      language: 'fr',
      currency: 'MAD',
      newsletter: false,
      notifications: true,
    },
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: 'user-003',
    email: 'marie.dupont@email.fr',
    firstName: 'Marie',
    lastName: 'Dupont',
    phone: '+33 6 12 34 56 78',
    address: {
      street: '789 Rue de la Paix',
      city: 'Paris',
      postalCode: '75001',
      country: 'France',
      isDefault: true,
    },
    preferences: {
      language: 'fr',
      currency: 'EUR',
      newsletter: true,
      notifications: true,
    },
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-10'),
  },
];

// Fonction pour charger les utilisateurs depuis localStorage
const loadUsersFromStorage = (): User[] => {
  if (typeof window === 'undefined') return mockUsers;
  
  try {
    const storedUsers = localStorage.getItem('users');
    if (storedUsers) {
      const parsedUsers = JSON.parse(storedUsers);
      // Fusionner avec les utilisateurs par défaut pour éviter de les perdre
      const existingEmails = parsedUsers.map((u: User) => u.email.toLowerCase());
      const defaultUsers = mockUsers.filter(u => !existingEmails.includes(u.email.toLowerCase()));
      return [...defaultUsers, ...parsedUsers];
    }
  } catch (error) {
    // Erreur lors du chargement des utilisateurs
  }
  
  return mockUsers;
};

// Fonction pour sauvegarder les utilisateurs dans localStorage
export const saveUsersToStorage = (users: User[]) => {
  if (typeof window === 'undefined') return;
  
  try {
    // Sauvegarder seulement les utilisateurs créés (pas les utilisateurs par défaut)
    const defaultEmails = mockUsers.map(u => u.email.toLowerCase());
    const createdUsers = users.filter(u => !defaultEmails.includes(u.email.toLowerCase()));
    localStorage.setItem('users', JSON.stringify(createdUsers));
  } catch (error) {
    // Erreur lors de la sauvegarde des utilisateurs
  }
};

// Fonction pour recharger les utilisateurs depuis localStorage
export const reloadUsersFromStorage = () => {
  if (typeof window !== 'undefined') {
    db.users = loadUsersFromStorage();
  }
};

// Base de données simulée
export const db = {
  products: [
    ...ceramicsProducts,
    ...jewelryProducts,
    ...decorationProducts,
    ...textilesProducts,
  ],
  categories,
  users: mockUsers, // Initialiser avec mockUsers par défaut
  carts: [] as Cart[],
  orders: [] as Order[],
};

// Fonctions utilitaires pour la base de données
export const getProductsByCategory = (categorySlug: string): Product[] => {
  return db.products.filter(product => product.categorySlug === categorySlug);
};

export const getProductById = (id: string): Product | undefined => {
  return db.products.find(product => product.id === id);
};

export const getCategoryBySlug = (slug: string): Category | undefined => {
  return db.categories.find(category => category.slug === slug);
};
